# Generated by Django 5.0.6 on 2024-05-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('text_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mailing', models.DateTimeField(verbose_name='Время и дата первой отправки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('launched', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=9, verbose_name='статус рассылки')),
                ('periodicity', models.CharField(choices=[('every day', 'Раз в день'), ('every week', 'Раз в неделю'), ('every month', 'Раз в месяц')], max_length=20, verbose_name='Периодичность рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_messages.textmessage', verbose_name='Сообщение')),
                ('to_client', models.ManyToManyField(to='clients.client', verbose_name='Клиенту')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('first_mailing',),
            },
        ),
        migrations.CreateModel(
            name='TryMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('success', 'успешно'), ('fail', 'не успешно')], max_length=10, verbose_name='статус попытки')),
                ('server_respond', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ('last_try',),
            },
        ),
    ]
