# Generated by Django 5.0.6 on 2024-05-29 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='last_mailing',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата последней отправки'),
            preserve_default=False,
        ),
    ]
