# Generated by Django 5.0.6 on 2024-06-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='рассылка активна'),
        ),
    ]
