# Generated by Django 5.0.6 on 2024-06-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('first_mailing',), 'permissions': [('set_active', 'Can activate/deactivate newsletter')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
