# Generated by Django 5.0.6 on 2024-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='содержимое статьи')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='изображение')),
                ('counts_of_view', models.SmallIntegerField(default=0, verbose_name='количество просмотров')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
